### ISSUE TITLE
Tidy up some of the extra stuff

### ISSUE THREAD

**Issue by sgibson91** [sgibson91/cross-stitch-carpentry#20]
In the future, we may want to tidy up some of the "extras", e.g.:

- [ ] Fill out `_extras/guide.md` with Instructor Guidelines
- [x] Fill out `_extras/discuss.md` with a further reading list (PR: #44)
- [x] Expand the repo's readme (PR: #22)
- [x] Prerequisites file (Issue: #39, PR: #40)
